### ISSUE TITLE
Using LIMES in a Streaming Context

### ISSUE THREAD

**Issue by Maatary** [dice-group/LIMES#161]
Hi, 

hereby i'm reaching out to learn a bit more about the Limes Framework. I'm particularly interested in finding out about the capacity to use the framework in a streaming rather than batching context. In particular, I would like to know if it posses a functionality like Silk in its Server version, witch is basically matching entity as the data comes in.  Another, question around that would be, if the functionality does not exist, is it something that could be implemented as an extension of what already exist ? Is the current state of the framework amenable to that ?

**Comment by Kleanthi** [comment]
Hey there! Thanks for your interest in LIMES.
For the moment, the data from the defined endpoints is loaded and then the linking begins.
However we are planning in the future to add such functionality.
Regarding the server, @kvndrsslr can answer your question.

**Comment by Maatary** [comment]
Thank you for your answer, I wonder if I could help with that effort. If there is any details documentation that could help understand the current architecture better that would be helpful

**Comment by kvndrsslr** [comment]
Hello Maatary, the official documentation at https://dice-group.github.io/LIMES/ is the most detailed we have right now.
Streaming is not implemented in the Framework, but we are currently playing around with big data platforms (namely, Flink and Spark).
With version 2.0 LIMES might see support for either or both, in effect also enabling streaming applications. For now, you would need to stick to batch processing.
You could try to do streaming in a micro batching manner, but I'd think that currently, this won't be very fast. However, if you want to try that, you would need to pass one of the datasets as a whole - so to guarantee complete mappings - but you could split the second into arbitrary smaller chunks and apply LIMES on each of them. Since we cache serialized objects to reduce initialization time, if the dataset you load as a whole is not too big, this should have okay-ish performance, but obviously the latency is far from what will be achievable using flink or spark.

Concerning your other question - we're always happy to accept helpful pull requests in the future, but since the incorporation of flink / spark into LIMES will require a lot of re-engineering, there is nothing you can do just now.

I'm closing this issue now.
