### ISSUE TITLE
About some metrics

### ISSUE THREAD

**Issue by jtrillos** [dice-group/LIMES#191]
Hi, 

I am evaluating the metrics to see which is the best String metric to apply on my project. And when I tried to use some of them, it returns me nothing. My acceptance is 0.9 and review 0.1.

For example, I notice that LIMES cannot identify a link between "ocean" and "oceans" to the Levenshtein distance metric.
`	<METRIC> Levenshtein(x.foaf:name, y.skos:prefLabel) </METRIC>`

I thought it was that I create wrong the configuration file but when I tried it with Qgrams it returns that there is a similarity of 0.75.
`	<METRIC> Qgrams(x.foaf:name, y.skos:prefLabel) </METRIC>`

Can someone help me to understand why is not returning something?

**Comment by Kleanthi** [comment]
Hi, thanks for using LIMES.
The issue you raised has to do with how each string similarity interprets the similarity between two instances. So for qgrams you might have a similarity 0.75 and then for Levenshtein you probably get a similarity that is below 0.9, so that's why you can't see the link in your output. If you need further reading, I suggest you take a look at how Levenshtein is implemented here: https://github.com/magsilva/SimMetrics/blob/master/src/uk/ac/shef/wit/simmetrics/similaritymetrics/Levenshtein.java since we are also using this implementation in LIMES.

**Comment by kvndrsslr** [comment]
LIMES will normalize edit distance (d) to similarity (s) via `s=1/(1+d)` so for the edit distance 1 per your example you need to set threshold to at least 0.5.
