### ISSUE TITLE
I can't upload my local file to web ui

### ISSUE THREAD

**Issue by Tomz7** [dice-group/LIMES#225]
Hello,

I can't upload my local file to web ui. I made the configurations but it doesn't work.
Plearse, I need you help.
Please find below the RDF file and the configuration file:

RDF file: 

<?xml version="1.0"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
             xmlns:contact="http://www.w3.org/2000/10/swap/pim/contact#">

  <contact:Person rdf:about="http://www.w3.org/People/EM/contact1">
    <contact:fullName>Eric Miller</contact:fullName>
	<contact:tel>0125365878</contact:tel>
    <contact:personalTitle>Dr.</contact:personalTitle> 
  </contact:Person>
  
   <contact:Person rdf:about="http://www.w3.org/People/EM/contact2">
    <contact:fullName>dert</contact:fullName>
	<contact:tel>0125365878</contact:tel>
    <contact:personalTitle>m.</contact:personalTitle> 
  </contact:Person>

</rdf:RDF>

Configuation file:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
<PREFIX>
  <NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
  <LABEL>rdf</LABEL>
</PREFIX>
<PREFIX>
  <NAMESPACE>http://www.w3.org/2000/10/swap/pim/contact</NAMESPACE>
  <LABEL>contact</LABEL>
</PREFIX>
<PREFIX>
  <NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
  <LABEL>rdfs</LABEL>
</PREFIX>
<SOURCE>
  <ID>sourceId</ID>
  <ENDPOINT>D:\Web\Person.rdf</ENDPOINT>
  <VAR>?s</VAR>
  <PAGESIZE>1000</PAGESIZE>
  <RESTRICTION></RESTRICTION>
  <PROPERTY>contact:fullName</PROPERTY>
  <PROPERTY>contact:tel</PROPERTY>
  <PROPERTY>contact:personalTitle</PROPERTY>
	

  <TYPE>rdf</TYPE>
</SOURCE>
<TARGET>
  <ID>targetId</ID>
  <ENDPOINT>D:\Web\Person.rdf</ENDPOINT>
  <VAR>?t</VAR>
  <PAGESIZE>1000</PAGESIZE>
  <RESTRICTION></RESTRICTION>
  <PROPERTY>contact:fullName</PROPERTY>
  <PROPERTY>contact:tel</PROPERTY>
  <PROPERTY>contact:personalTitle</PROPERTY>

  <TYPE>rdf</TYPE>
</TARGET>
<METRIC>
  cosine(s.rdfs:fullName,t.rdfs:fullName)
</METRIC>
<ACCEPTANCE>
  <THRESHOLD>0.98</THRESHOLD>
  <FILE>accepted.nt</FILE>
  <RELATION>owl:sameAs</RELATION>
</ACCEPTANCE>
<REVIEW>
  <THRESHOLD>0.9</THRESHOLD>
  <FILE>reviewme.nt</FILE>
  <RELATION>owl:sameAs</RELATION>
</REVIEW>
<EXECUTION>
  <REWRITER>DEFAULT</REWRITER>
  <PLANNER>DEFAULT</PLANNER>
  <ENGINE>DEFAULT</ENGINE>
</EXECUTION>
<OUTPUT>TAB</OUTPUT>
</LIMES>

**Comment by Tomz7** [comment]
Please find below the RDF file and the configuration file

[configuration.txt](https://github.com/dice-group/LIMES/files/4318692/configuration.txt)
[Person.txt](https://github.com/dice-group/LIMES/files/4318695/Person.txt)

**Comment by Kleanthi** [comment]
Does it work when you are using LIMES from command line?

**Comment by Tomz7** [comment]
> Does it work when you are using LIMES from command line?
> Can you please report the error you are receiving when you try to load it via the GUI?

Even the installation of the desktop GUI is problematic, I get the following error message

**Comment by Tomz7** [comment]
![unnamed](https://user-images.githubusercontent.com/62064555/76542806-d4b0b580-6485-11ea-876d-1a49ca742a7b.png)

**Comment by Kleanthi** [comment]
Hello again! Have you tried to compile LIMES and create a .jar file following the guidelines from https://github.com/dice-group/LIMES/blob/master/README.md and from http://dice-group.github.io/LIMES/#/getting_started/installation ?

_Deprecation Note: LIMES provided a graphical user interface (GUI) up to version 1.6.2. However, this GUI was dropped in favour of a modern Web GUI that runs in the browser and is included in the limes-core module. Therefore, no additional installation is needed for the modern Web GUI. If you still want to use the old GUI, you need to use LIMES version 1.6.2 or below._ 

Also your file extension should be .ttl and not .txt

**Comment by Tomz7** [comment]
yes I tried to compile with version 1.7.1 and I have a jar file but how do I run this jar file?

**Comment by Tomz7** [comment]
I use an .nt file

**Comment by Tomz7** [comment]
I used the same two files and made a cosine between them, but I didn't get anything out of it.
here's what I did in the web ui
![1](https://user-images.githubusercontent.com/62064555/76546696-3f64ef80-648c-11ea-934f-6fc1efc52e4b.PNG)
![2](https://user-images.githubusercontent.com/62064555/76546699-3ffd8600-648c-11ea-895a-d76f3cadde31.PNG)
![3](https://user-images.githubusercontent.com/62064555/76546700-40961c80-648c-11ea-8f08-9a79c121cdd6.PNG)
![4](https://user-images.githubusercontent.com/62064555/76546798-63c0cc00-648c-11ea-8a84-7e94d027c544.PNG)

**Comment by Kleanthi** [comment]
First, there are instructions on how to run the .jar file here: http://dice-group.github.io/LIMES/#/user_manual/running_limes?id=running-limes

Second, the configuration file should either be an "XML" (default) or an "RDF" file.

Third, based on your screenshots, I do not see an error message. Have you checked if there are any output files produced, even empty? For example, if there are output files but they are empty, there is a chance that no pairs were produced because e.g. your acceptance threshold is too high. Can you try and use a lower threshold like 0.5 and repeat the process?

**Comment by Kleanthi** [comment]
Instructions on how to use the GUI and what each button does, can be found here:
http://dice-group.github.io/LIMES/#/user_manual/running_limes?id=using-the-web-ui

**Comment by Tomz7** [comment]
i don't have an output file when i run with the web ui

**Comment by Kleanthi** [comment]
Have you tried to lower the threshold?
Can you please try to execute LIMES via the command line using your initial threshold and the new lower threshold?

**Comment by Kleanthi** [comment]
So basically, I am trying to figure out if the problem has to do with LIMES in general, or the issue is located in the GUI, or if there is a problem with your system/files etc.

To do so, please follow the next steps:
-Clone or download the latest version of LIMES in one of your folders. If you have already done this, please do it again, in a new folder, it is important.
-Follow the steps in here: https://github.com/dice-group/LIMES/blob/master/README.md on how to create an executable .jar file. Then follow the instructions here: http://dice-group.github.io/LIMES/#/user_manual/running_limes?id=using-the-cli-client on how to execute the .jar file via command line. You can experiment with your configuration parameters in case you do not get an output file. Also you can try running LIMES using some of the datasets found here: https://github.com/dice-group/LIMES/tree/master/limes-core/src/main/resources/datasets to make sure that there is at least one configuration that produces results for LIMES via command line.
-Since your goal is to use LIMES via a graphical interface, the desktop GUI has been **deprecated** after version 1.6.2, but you can use LIMES Web GUI. To do so, follow the instruction listed here: http://dice-group.github.io/LIMES/#/user_manual/running_limes?id=using-the-web-ui
-If you have one or more configurations that worked when running LIMES via the command line, please use these configurations in the Web GUI. If you do not get ANY results from any valid configuration, please let us know, cause that indicates a problem with the Web GUI.

**Comment by kvndrsslr** [comment]
Closing this as its become stale
