### ISSUE TITLE
how can i get the output file from web-ui?

### ISSUE THREAD

**Issue by kaister3** [dice-group/LIMES#227]

**Comment by Kleanthi** [comment]
From the user manual (http://dice-group.github.io/LIMES/#/user_manual/running_limes?id=using-the-web-ui):
_Acceptance and review conditions
In this component you can define the Acceptance Threshold and the Review Threshold. In addition, you can rename the names of files, **which can be created after execution**. Besides, you can change the Relation. Instead of prefix you can write the namespace and its respective URI will be automatically found by the interface, converted to a prefix (if it exists in prefix.cc, otherwise you have to manually add it)_

So you define the name of the output file (preferably full path) and after execution you will find your links there.
