### ISSUE TITLE
owl:sameAs is not implemented yet message

### ISSUE THREAD

**Issue by pskLana** [dice-group/LIMES#248]
Limes throws the message, saying that owl:sameAs is not implemented yet. The actual functionality works for me. So I guess it is just a message. Please, remove it, if it is unnecessary. The screenshot from the colleague who encountered this issue is shown below.
![image_limes](https://user-images.githubusercontent.com/48616148/119128805-69258900-ba36-11eb-9bc4-a075e15c3e43.png)

Probably, the matching relationship is passed to the ExecutionEngineFactory.

**Comment by abdullahfathi** [comment]
LIMES implements three execution engines (default, simple, and partial recall) so LIMES will through a message when the execution engine is not one of already implemented engines telling you that the name you entered during LIMES configuration(either manually or via a configuration file) is not implemented yet and LIMES will use the default execution engine. This will not affect the functionality of LIMES because LIMES will use the default execution engine in this case
